$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
inputs:
  data: 
    type: uri_file
    path: azureml:hourly:1
  test_train_ratio: 0.2
  learning_rate: 0.25
  registered_model_name: job_model
code: src
command: python main.py --data ${{inputs.data}} --test_train_ratio ${{inputs.test_train_ratio}} --learning_rate ${{inputs.learning_rate}} --registered_model_name ${{inputs.registered_model_name}}
environment: azureml:bike-share-train-env:1
compute: azureml:cpu-cluster
experiment_name: bike-share-exp
display_name: cluster-job