name: ci-workflow
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches: 
    - qa
    
jobs:
  sample-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.2
      - name: Login to Az Cli
        uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}   #setup: provide your Azure credentials name stored in github
          client-id: ${{ secrets.SP_CLIENT_ID }}
          client-secret: ${{ secrets.SP_CLIENT_SECRET }}
          tenant-id: ${{ secrets.SP_TENANT_ID }}

      - name: Install az ml & set default values for AML
        run: | 
          az extension add -n ml -y --version 2.2.1
          az configure --defaults group=${{ secrets.AZ_RG }} workspace=${{ secrets.AZ_WORKSPACE }} location=${{ secrets.AZ_LOCATION }}  
      - name: run training and model validation
        run: |
         az ml job create --stream --file supporting_files/train_job/job.yml

      - name:  Create Pull Request to Main
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }} 
          head: ${{ github.ref }}
          base: main
          title: "An automatically created PR to main by successful CI"
